name: Dependency
description: 'Installs dependencies needed for cv compilation'

runs:
  using: "composite"
  steps:
    - name: Updates repositories and installs packages
      shell: bash
      run: |
        sudo apt update
        sudo apt install --assume-yes build-essential wget context

    - name: Downloads and installs pandoc
      shell: bash
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.11.1/pandoc-2.11.1-1-amd64.deb
        sudo apt install ./pandoc-2.11.1-1-amd64.deb
        rm pandoc-2.11.1-1-amd64.deb

    - name: Cleans system
      shell: bash
      run: |
        sudo apt remove --assume-yes wget
        sudo apt autoclean
        sudo apt clean
